FizzBuzzAssesment.Web/Models/FizzBuzzRequest.cs
namespace FizzBuzzAssesment.Web.Models
{
    using System.ComponentModel.DataAnnotations;
    using FizzBuzz.Models;
    using PagedList;

    /// <summary>
    /// Class for fiz buzz request model.
    /// </summary>
    public class FizzBuzzRequest
    {
        /// <summary>
        /// Gets or sets number.
        /// </summary>
        [Required(ErrorMessage = "Number is required")]
        [Range(1, 1000, ErrorMessage = "Number should be between 1 to 1000")]
        public int? Number { get; set; }

        /// <summary>
        /// Gets or sets fizzBuzzListValue.
        /// </summary>
        public IPagedList<FizzBuzzModel> FizzBuzzList { get; set; }
    }
}

FizzBuzzAssesment.Web/Controllers/ErrorController.cs
namespace FizzBuzzAssesment.Web.Controllers
{
    using System.Web.Mvc;

    /// <summary>
    /// Class for Error Controller.
    /// </summary>
    public class ErrorController : Controller
    {
        // GET: Error

        /// <summary>
        /// Index action nmethod to return view.
        /// </summary>
        /// <returns>View.</returns>
        public ActionResult Index()
        {
            return this.View("CustomError");
        }

        /// <summary>
        /// Action method to return custom error view.
        /// </summary>
        /// <returns>View.</returns>
        public ActionResult CustomError()
        {
            return this.View();
        }
    }
}

FizzBuzzAssesment.Web/Controllers/FizzBuzzController.cs
namespace FizzBuzzAssesment.Web.Controllers
{
    using System.Collections.Generic;
    using System.Web.Mvc;
    using FizzBuzz.Business.Interface;
    using FizzBuzz.Common.Helpers;
    using FizzBuzz.Models;
    using FizzBuzzAssesment.Web.Models;
    using PagedList;

    /// <summary>
    /// Controller for fizz buzz.
    /// </summary>
    public class FizzBuzzController : Controller
    {
        private static List<FizzBuzzModel> fizzBuzzList;
        private readonly IFizzBuzz fizzBuzz;

        /// <summary>
        /// Initializes a new instance of the <see cref="FizzBuzzController"/> class.
        /// </summary>
        /// <param name="fizzBuzz">Interface for IFizzBuzz</param>
        public FizzBuzzController(IFizzBuzz fizzBuzz)
        {
            this.fizzBuzz = fizzBuzz;
        }

        /// <summary>
        /// Action method to review Index view.
        /// </summary>
        /// <returns>View.</returns>
        public ActionResult Index()
        {
            return this.View(new FizzBuzzRequest());
        }

        /// <summary>
        /// Action method to get the list of generated fizz buzz number list.
        /// </summary>
        /// <param name="model">Request model.</param>
        /// <param name="page">Page number.</param>
        /// <returns>List of generated numbers.</returns>
        [HttpPost]
        public ActionResult GenerateFizzBuzz(FizzBuzzRequest model, int page = 1)
        {
            if (this.ModelState.IsValid)
            {
                fizzBuzzList = this.fizzBuzz.GetNumbers(model.Number.Value);
                model.FizzBuzzList = this.GetPagedList(page);
            }

            return this.View("Index", model);
        }

        /// <summary>
        /// Action method to get the pagination fizz buzz generated data.
        /// </summary>
        /// <param name="number">Input number.</param>
        /// <param name="page">Page number.</param>
        /// <returns>List of generated number list.</returns>
        [HttpGet]
        public ActionResult GenerateFizzBuzzPagedData(int number, int page)
        {
            FizzBuzzRequest resModel = new FizzBuzzRequest
            {
                Number = number,
                FizzBuzzList = this.GetPagedList(page),
            };
            return this.View("Index", resModel);
        }

        /// <summary>
        /// Method used to get paged list data.
        /// </summary>
        /// <param name="page">Page number.</param>
        /// <returns>Paged list data.</returns>
        [NonAction]
        protected IPagedList<FizzBuzzModel> GetPagedList(int page)
        {
            return fizzBuzzList.ToPagedList(page, Constants.MaxPageSize);
        }
    }
}

FizzBuzzAssesment.Web/Views/FizzBuzz/Index.cshtml
@model FizzBuzzAssesment.Web.Models.FizzBuzzRequest
@using PagedList.Mvc;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="panel panel-body">
    @using (Html.BeginForm("GenerateFizzBuzz", "FizzBuzz", FormMethod.Post))
    {
        <p>
            @Html.LabelFor(m => m.Number)
            @Html.TextBoxFor(m => m.Number, new { @autocomplete = "off", @min = "1", @max = "1000", @maxlength = "4" })
            <input type="submit" class="" value="Generate" />
            @Html.ValidationMessageFor(m => m.Number)
        </p>
    }
    @if (Model != null && Model.FizzBuzzList != null && Model.FizzBuzzList.Count > 0)
    {
        <table class="table">
            <tr>
                <th>
                    Number List
                </th>
                <th></th>
            </tr>
            @for (int i = 0; i < Model.FizzBuzzList.Count; i++)
            {
                <tr>
                    <td>
                        @foreach (var value in Model.FizzBuzzList[i].Value.Split(' '))
                        {
                            <font class="@value">@value</font>
                        }
                    </td>
                </tr>
            }
        </table>

        @Html.PagedListPager(
                            Model.FizzBuzzList,
                            page => Url.Action("GenerateFizzBuzzPagedData", new { Model.Number, page }),
                            PagedListRenderOptions.Classic)
    }
</div>
@*<div class="jumbotron">
        @using (Html.BeginForm("GenerateFizzBuzz", "FizzBuzz", FormMethod.Post))
        {
            @Html.LabelFor(m => m.Number, new { @class = "text-primary" })
            <span></span>
            @Html.TextBoxFor(m => m.Number, new { @autocomplete = "off", @min = "1", @max = "1000", @maxlength = "4" })
            <input type="submit" class="btn btn-primary" value="Submit" />
            @Html.ValidationMessageFor(m => m.Number)
        }

        @if (Model != null && Model.FizzBuzzList != null && Model.FizzBuzzList.Count > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th class="col-lg-6">Result</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.FizzBuzzList.Count; i++)
                    {
                        <tr>
                            <td scope="row">
                                @foreach (var value in Model.FizzBuzzList[i].Value.Split(' '))
                                {
                                    <font class="@value">@value</font>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            @Html.PagedListPager(Model.FizzBuzzList, page => Url.Action("GenerateFizzBuzzPagedData", new { Model.Number, page }), PagedListRenderOptions.TwitterBootstrapPager)
        }
    </div>*@

FizzBuzzAssesment.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FizzBuzzAssesment.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FizzBuzzAssesment.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

FizzBuzzAssesment.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fizz Buzz Assessment</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fizz Buzz", "Index", "FizzBuzz", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>